# Generated by Django 5.2.5 on 2025-12-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddQues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ques', models.CharField()),
                ('op1', models.CharField()),
                ('op2', models.CharField()),
                ('op3', models.CharField()),
                ('op4', models.CharField()),
            ],
        ),
    ]
