# Generated by Django 5.2.5 on 2026-01-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addques',
            name='correct',
            field=models.CharField(default='op1', max_length=300),
        ),
        migrations.AlterField(
            model_name='addques',
            name='Ques',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='addques',
            name='op1',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='addques',
            name='op2',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='addques',
            name='op3',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='addques',
            name='op4',
            field=models.CharField(max_length=300),
        ),
    ]
