# Generated by Django 5.2.5 on 2026-01-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_addques_correct_alter_addques_ques_alter_addques_op1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addques',
            name='category',
            field=models.CharField(default='python', max_length=200),
        ),
    ]
