# Generated by Django 5.2.5 on 2026-01-05 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_addcategory_userreg_alter_addques_ques_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReg',
        ),
    ]
