# Generated by Django 5.2.5 on 2026-01-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_delete_userreg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcategory',
            old_name='name',
            new_name='CategoryName',
        ),
        migrations.AddField(
            model_name='addcategory',
            name='CategoryDescription',
            field=models.TextField(default='This is a computer programming language'),
        ),
    ]
