# Generated by Django 5.2.5 on 2026-01-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_rename_name_addcategory_categoryname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('education', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('photo', models.ImageField(upload_to='profile_photos/')),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='addques',
            name='correct',
            field=models.TextField(default='op1', max_length=300),
        ),
    ]
