# Generated by Django 5.2.5 on 2026-01-09 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_userregister_alter_addques_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.addcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.userregister')),
            ],
        ),
    ]
