# Generated by Django 5.2.5 on 2026-01-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_userscore_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='total_questions',
            field=models.IntegerField(default=10),
        ),
    ]
