# Generated by Django 5.2.5 on 2026-01-10 06:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_userscore_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
